### ISSUE TITLE
DATASET

### ISSUE THREAD

**Issue by zjy9779** [jnoat92/atrous-cGAN-for-SAR-optical-synthesis#1]
Which dataset do you use in your article?

**Comment by jnoat92** [comment]
I used three datasets, two of them are public:
I. Del’Arco Sancheset al., “Campo verde database: Seeking to improve agricultural remote sensing of tropical areas,” IEEE Geosci. RemoteSens. Lett., vol. 15, no. 3, pp. 369–373, Mar. 2018.

I. D. Sancheset al., “LEM benchmark database for tropical agricultural remote sensing application,” Int. Arch. Photogramm., Remote Sens.Spatial Inf. Sci., vol. 42, no. 1, pp. 387–392, Sep. 2018.

**Comment by zjy9779** [comment]
> 
> 
> I used three datasets, two of them are public:
> I. Del’Arco Sancheset al., “Campo verde database: Seeking to improve agricultural remote sensing of tropical areas,” IEEE Geosci. RemoteSens. Lett., vol. 15, no. 3, pp. 369–373, Mar. 2018.
> 
> I. D. Sancheset al., “LEM benchmark database for tropical agricultural remote sensing application,” Int. Arch. Photogramm., Remote Sens.Spatial Inf. Sci., vol. 42, no. 1, pp. 387–392, Sep. 2018.

Thank you. But, currently, the LEM dataset is no longer available for download. Could you share this with me?

**Comment by jnoat92** [comment]
Sorry by the delay, the LEM dataset is here: http://www.dpi.inpe.br/agricultural-database/lem/
