### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by ooolike** [jnoat92/atrous-cGAN-for-SAR-optical-synthesis#2]
FileNotFoundError: [Errno 2] No such file or directory: '../datasets/Amazonia_Legal/Landsat_8/Reference/REFERENCE_2018_EPSG32620.npy'
This is caused by the lack of dataset, right ?o(╥﹏╥)o

**Comment by jnoat92** [comment]
Hello @ooolike . Yes, that is the reason
